version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: portfolio_qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage
    # restart: unless-stopped
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - portfolio_network

  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: portfolio_ollama
  #   ports:
  #     - "11434:11434"
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   restart: unless-stopped
  #   networks:
  #     - portfolio_network
  #   environment:
  #     - OLLAMA_KEEP_ALIVE=1h
  #     - OLLAMA_HOST=0.0.0.0
  #     - NVIDIA_VISIBLE_DEVICES=all
  #     - NVIDIA_DRIVER_CAPABILITIES=compute,utility
  #   entrypoint: >
  #     /bin/sh -c "
  #     ollama serve
  #     "
      
  api:
    build: ./api
    container_name: portfolio_api
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --log-level info --reload
    # command: sleep infinity
    ports:
      - "8000:8000"
    volumes:
      - ./api/src:/api/src
    # restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./api/.env
    networks:
      - portfolio_network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d
      - web_static:/usr/share/nginx/html
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/www/certbot
    depends_on:
      - api
    networks:
      - portfolio_network

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email crtquiza@gmail.com --agree-tos --no-eff-email -d cristhianquiza.com

volumes:
  web_static:
  certbot_etc:
  certbot_var:
  qdrant_storage:
    driver: local
  # ollama_data:
  #   driver: local

networks:
  portfolio_network:
    driver: bridge